## Available Geomarkers

Cole Brokamp   
cole.brokamp@cchmc.org

### Level 1

| **Database** | **Example Data** | **Space** | **Time** |
| --------------------- | ---------------------------- | --------- | --------- |
| Topologically Integrated Geographic Encoding and Referencing (TIGER) | Proximity to roadway by type, locations of airports, railroads, bodies of water, elevation | Exact location (nationwide) | Yearly |
| Open Street Map (OSM) | Public transportation routes | Exact location | Current |
| Global Historical Climatology Network (GHCN) | Temperature, relative humidity, precipitation, wind speed and direction | Interpreted from &gt; 5000 stations (nationwide) | Daily |
| National Emissions Inventory (NEI) | Location and amount of emissions | Exact location | Yearly |
| EPA Air Quality System (AQS) | Fixed site monitoring of ambient pollutant levels, air quality alerts | Interpreted from over 2500 stations (nationwide) | Daily |
| US Department of Transportation (DOT) | Highway traffic intensity | Exact location (nationwide) | Yearly |

### Level 2

| **Database** | **Example Data** | **Space** | **Time** |
| --------------------- | ---------------------------- | --------- | --------- |
| US Census American Community Survey (ACS) | Population, socioeconomic indicators | Census tract or block (nationwide) | Yearly |
| North American Regional Reanalysis (NARR) | Air temperature, planetary boundary height, relative humidity, precipitation, wind | North America (0.3°×0.3°) | 8-times (2001 – 2016); daily means (1979 – 2000) |
| Moderate Resolution Imaging Spectroradiometer (MODIS) | Greenspace, land cover, aerosol optical thickness, surface reflectance | 3km square grids (nationwide) | Daily (2000 – 2015) |
| National Land Cover Database (NLCD) | 21 classes of land cover classifications | 30 x 30 m grid | Annual (1992, 2001, 2006, 2011) |
| Smart Location Database (SLD) | Location efficiency, characteristics of the built environment | Census tract | 2010 |
| Modified Retail Food Environment Index (mRFEI) | Fraction of food retailers that are &quot;healthy&quot; | Census Tract | 2011 |
| USDA National Agricultural Statistics Service (NASS) | Quantity of types of animals, products, crops | Zip Code | 1997, 2002, 2007, 2008, 2011 - 2016 |

### Level 3

| **Database** | **Example Data** | **Space** | **Time** |
| --------------------- | ---------------------------- | --------- | --------- |
| Spatiotemporal PM2.5 Predictions | Estimated air pollution exposure | Tract Centers (Contiguous U.S.) | Monthly (1999 – 2008) |
| Spatiotemporal PM2.5 Predictions | Estimated air pollution exposure | Global (0.01°×0.01°) | Annual (1998 – 2014) |
| Spatiotemporal NO2 Predictions | Estimated NO2 exposure | Census block centers; block group; tract |  Monthly (2000 – 2010) |
| National Park Service Geospatial Sound Modeling (GSM) | Noise level | 270 m sq grids (nationwide) | 2015 |

### Greater Cincinnati Area Only
| **Database** | **Example Data** | **Space** | **Time** |
| --------------------- | ---------------------------- | --------- | --------- |
| Cincinnati Area Geographic Information Systems (CAGIS) | Crime density, combined sewer overflow sites, housing infractions, urban tree cover, etc | Exact location (Greater Cincinnati Area) | Current |
| Uber Move | Estimated travel time by car | Census tract and traffic analysis area | Hourly (2016-2017) |
| Metropolitan Sewer District (MSD) | Combined Sewer Overflow events | Exact location | Daily (2012 - 2016) |
| Hamilton County Auditor | Home images, value, age, other physical characteristics, owner name | Exact | Inspection dates
| Urban Tree Canopy (UTC) Assessments | Land cover in 6 categories: impervious, tree canopy, agriculture, bare soil, grass/meadow, water | 1 x 1 m (Cincinnati and Northern Kentucky) | 2010 |
| Normalized Differential Vegetation (NDVI) cover | Satellite measured near-infrared and visible radiation | 30 x 30 m (seven county region) | 2000 & 2010|
| Cincinnati Metro Housing Authority (CMHA) | Vacant properties, managed and vouchered properties, management companies | Exact location (Greater Cincinnati Area) | Current |
| Land Use Random Forest | PM2.5 components: Al, Cu, Fe, K, Mn, Pb, S, Si, V, Zn | Exact location | Average daily exposure (2002-2006) |
| Cincinnati Space Time PM2.5 Model | Estimated air pollution exposure | Exact location (seven county area served by CCHMC) | Daily (2000 – 2015) |