#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
input_path <- if (length(args) >= 1) args[[1]] else "src/pubs.yaml"
output_path <- if (length(args) >= 2) args[[2]] else "colebrokamp.bib"

special_chars <- c(
  "\\" = "\\textbackslash{}",
  "{" = "\\{",
  "}" = "\\}",
  "&" = "\\&",
  "%" = "\\%",
  "$" = "\\$",
  "#" = "\\#",
  "_" = "\\_",
  "\u2013" = "--",
  "\u2014" = "---",
  "\u2212" = "-",
  "\u2019" = "'",
  "\u2018" = "'",
  "\u201c" = "``",
  "\u201d" = "''",
  "\u2026" = "\\ldots{}",
  "\u00c1" = "{\\'A}",
  "\u00c9" = "{\\'E}",
  "\u00cd" = "{\\'I}",
  "\u00d3" = "{\\'O}",
  "\u00da" = "{\\'U}",
  "\u00e1" = "{\\'a}",
  "\u00e9" = "{\\'e}",
  "\u00ed" = "{\\'i}",
  "\u00f3" = "{\\'o}",
  "\u00fa" = "{\\'u}",
  "\u00d6" = "{\\\"O}",
  "\u00dc" = "{\\\"U}",
  "\u00f6" = "{\\\"o}",
  "\u00fc" = "{\\\"u}",
  "\u00e7" = "{\\c{c}}",
  "\u00e3" = "{\\~a}",
  "\u00a0" = " "
)

latex_escape <- function(value) {
  text <- paste(as.character(value), collapse = "")
  chars <- strsplit(text, "", useBytes = FALSE)[[1]]
  escaped <- vapply(
    chars,
    function(char) {
      if (char %in% names(special_chars)) {
        special_chars[[char]]
      } else {
        char
      }
    },
    character(1),
    USE.NAMES = FALSE
  )
  paste0(escaped, collapse = "")
}

present <- function(value) {
  !is.null(value) &&
    length(value) > 0 &&
    !all(is.na(value)) &&
    nzchar(trimws(as.character(value)[[1]]))
}

normalize_doi <- function(value) {
  if (!present(value)) {
    return(NULL)
  }

  doi <- trimws(as.character(value)[[1]])
  doi <- sub("^https?://(dx[.])?doi[.]org/", "", doi, ignore.case = TRUE)
  doi <- sub("^doi:", "", doi, ignore.case = TRUE)
  doi <- trimws(doi)

  if (startsWith(doi, "10.")) doi else NULL
}

regex_parts <- function(pattern, text) {
  match <- regexec(pattern, text, perl = TRUE)
  parts <- regmatches(text, match)[[1]]
  if (length(parts) == 0) {
    return(NULL)
  }
  parts
}

parse_issue_pages <- function(value) {
  if (!present(value)) {
    return(list())
  }

  text <- trimws(as.character(value)[[1]])
  if (grepl("^in press$", text, ignore.case = TRUE)) {
    return(list(note = "In Press"))
  }

  parts <- regex_parts("^(\\d+)\\s*\\(([^)]+)\\)\\s*[:;]\\s*(.+)$", text)
  if (!is.null(parts)) {
    return(list(volume = parts[[2]], number = parts[[3]], pages = parts[[4]]))
  }

  parts <- regex_parts("^(\\d+)\\s*\\(([^)]+)\\)$", text)
  if (!is.null(parts)) {
    return(list(volume = parts[[2]], number = parts[[3]]))
  }

  parts <- regex_parts("^(\\d+(?:-\\d+)?)\\s*[:;]\\s*(.+)$", text)
  if (!is.null(parts)) {
    return(list(volume = parts[[2]], pages = parts[[3]]))
  }

  if (grepl("^e\\d+$", text, ignore.case = TRUE)) {
    return(list(pages = text))
  }

  parts <- regex_parts("^(.+?)\\s*;\\s*([A-Za-z]?\\d+\\S*(?:-\\S+)?)$", text)
  if (!is.null(parts)) {
    return(list(note = parts[[2]], pages = parts[[3]]))
  }

  list(note = text)
}

author_names <- function(value) {
  if (is.list(value) || length(value) > 1) {
    return(unlist(value, use.names = FALSE))
  }
  strsplit(as.character(value), "\\s*,\\s*", perl = TRUE)[[1]]
}

bibtex_entry <- function(key, pub) {
  fields <- c(
    list(
      title = pub[["title"]],
      author = paste(author_names(pub[["author"]]), collapse = " and "),
      journal = pub[["journal"]],
      year = as.character(pub[["year"]])
    ),
    parse_issue_pages(pub[["issue_pages"]])
  )

  if (present(pub[["pages"]])) {
    fields[["pages"]] <- as.character(pub[["pages"]])
  }

  doi <- normalize_doi(pub[["doi"]])
  if (!is.null(doi)) {
    fields[["doi"]] <- doi
  }
  if (present(pub[["pmid"]])) {
    fields[["pmid"]] <- as.character(pub[["pmid"]])
  }
  if (present(pub[["download_link"]])) {
    fields[["url"]] <- as.character(pub[["download_link"]])
  }

  lines <- vapply(
    names(fields),
    function(field_key) {
      escaped_value <- latex_escape(fields[[field_key]])
      if (field_key == "title") {
        escaped_value <- paste0("{", escaped_value, "}")
      }
      sprintf("  %s = {%s}", field_key, escaped_value)
    },
    character(1),
    USE.NAMES = FALSE
  )

  paste0("@article{", key, ",\n", paste(lines, collapse = ",\n"), "\n}")
}

publications <- yaml::read_yaml(input_path)

content <- c(
  sprintf("%% Generated from %s. Do not edit this file directly.", input_path),
  "% Regenerate with: Rscript scripts/pubs_yaml_to_bibtex.R",
  "",
  paste(
    vapply(
      names(publications),
      function(key) bibtex_entry(key, publications[[key]]),
      character(1)
    ),
    collapse = "\n\n"
  ),
  ""
)

writeLines(content, output_path, useBytes = TRUE)
message(sprintf("wrote %d entries to %s", length(publications), output_path))
