use std::collections::HashMap;

use crate::data::Publication;
use crate::text::{normalize_doi, present};

pub(crate) fn render(publications: &[Publication]) -> String {
    let cite_keys = cite_keys(publications);
    let entries = publications
        .iter()
        .zip(cite_keys.iter())
        .map(|(publication, key)| bibtex_entry(key, publication))
        .collect::<Vec<_>>()
        .join("\n\n");

    format!(
        "% Generated from data-raw/pubs.yaml. Do not edit this file directly.\n\
         % Regenerate with: just render bib\n\n{entries}\n"
    )
}

fn cite_keys(publications: &[Publication]) -> Vec<String> {
    let bases = publications.iter().map(cite_key_base).collect::<Vec<_>>();

    let mut totals = HashMap::new();
    for base in &bases {
        *totals.entry(base.clone()).or_insert(0_usize) += 1;
    }

    let mut seen = HashMap::new();
    bases
        .into_iter()
        .map(|base| {
            if totals[&base] == 1 {
                base
            } else {
                let count = seen.entry(base.clone()).or_insert(0_usize);
                *count += 1;
                format!("{base}{}", cite_key_suffix(*count))
            }
        })
        .collect()
}

fn bibtex_entry(key: &str, publication: &Publication) -> String {
    let mut fields = vec![
        ("title".to_string(), publication.title.clone()),
        ("author".to_string(), publication.author.join(" and ")),
        ("journal".to_string(), publication.journal.clone()),
        ("year".to_string(), publication.year.to_string()),
    ];

    add_field(&mut fields, "volume", publication.volume.as_deref());
    add_field(&mut fields, "number", publication.number.as_deref());
    add_field(&mut fields, "pages", publication.pages.as_deref());
    add_field(&mut fields, "note", publication.note.as_deref());

    if let Some(doi) = normalize_doi(publication.doi.as_deref()) {
        fields.push(("doi".to_string(), doi));
    }
    add_field(&mut fields, "pmid", publication.pmid.as_deref());
    add_field(&mut fields, "url", publication.url.as_deref());

    let lines = fields
        .into_iter()
        .map(|(field, value)| {
            let mut escaped = latex_escape(&value);
            if field == "title" {
                escaped = format!("{{{escaped}}}");
            }
            format!("  {field} = {{{escaped}}}")
        })
        .collect::<Vec<_>>()
        .join(",\n");

    format!("@article{{{key},\n{lines}\n}}")
}

fn add_field(fields: &mut Vec<(String, String)>, key: &str, value: Option<&str>) {
    if let Some(value) = present(value) {
        fields.push((key.to_string(), value.to_string()));
    }
}

fn cite_key_base(publication: &Publication) -> String {
    let surname = publication
        .author
        .first()
        .and_then(|author| author.split_whitespace().last())
        .map(slugify)
        .filter(|slug| !slug.is_empty())
        .unwrap_or_else(|| "publication".to_string());
    format!("{surname}-{}", publication.year)
}

fn cite_key_suffix(index: usize) -> String {
    let mut value = index;
    let mut suffix = String::new();
    while value > 0 {
        value -= 1;
        suffix.insert(0, (b'a' + (value % 26) as u8) as char);
        value /= 26;
    }
    suffix
}

fn slugify(value: &str) -> String {
    value
        .chars()
        .filter(|character| character.is_ascii_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

fn latex_escape(value: &str) -> String {
    value
        .chars()
        .map(|character| match character {
            '\\' => "\\textbackslash{}".to_string(),
            '{' => "\\{".to_string(),
            '}' => "\\}".to_string(),
            '&' => "\\&".to_string(),
            '%' => "\\%".to_string(),
            '$' => "\\$".to_string(),
            '#' => "\\#".to_string(),
            '_' => "\\_".to_string(),
            '–' => "--".to_string(),
            '—' => "---".to_string(),
            '−' => "-".to_string(),
            '’' | '‘' => "'".to_string(),
            '“' => "``".to_string(),
            '”' => "''".to_string(),
            '…' => "\\ldots{}".to_string(),
            'Á' => "{\\'A}".to_string(),
            'É' => "{\\'E}".to_string(),
            'Í' => "{\\'I}".to_string(),
            'Ó' => "{\\'O}".to_string(),
            'Ú' => "{\\'U}".to_string(),
            'á' => "{\\'a}".to_string(),
            'é' => "{\\'e}".to_string(),
            'í' => "{\\'i}".to_string(),
            'ó' => "{\\'o}".to_string(),
            'ú' => "{\\'u}".to_string(),
            'Ö' => "{\\\"O}".to_string(),
            'Ü' => "{\\\"U}".to_string(),
            'ö' => "{\\\"o}".to_string(),
            'ü' => "{\\\"u}".to_string(),
            'ç' => "{\\c{c}}".to_string(),
            'ã' => "{\\~a}".to_string(),
            ' ' => " ".to_string(),
            other => other.to_string(),
        })
        .collect()
}
